### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by janup2442**
Added my card

### CODE REVIEW

**Comment by janup2442** [comment]
@aparna03dubey  hello , I have added my card please merge it.

**Comment by aparna03dubey** [comment]
please resolve conflicts

**Comment by aparna03dubey** [comment]
Please resolve conflicts

**Comment by janup2442** [comment]
Ok , Wait. Sorry for being late .

**Comment by janup2442** [comment]
@aparna03dubey  done , I was thinking to redesign the Index.html page  for better UI. Should I ?

**Comment by aparna03dubey** [comment]
> @aparna03dubey done , I was thinking to redesign the Index.html page for better UI. Should I ?

Yes! Go Ahead

**Pull request merged**
