### PR TITLE
Modify style

### PR DESCRIPTION
**Pull request by janup2442**
- i have added all new , css style. I hope you like it.
- if you need any further modification or help , do let me know .
- color that i have choosen randomly . I am not good at choosing colors . 
- if you suggest me any good combination that you want do let me know.
please review the site and its transition on and hover effect , fonts and do let me know , how it is !..

thank you!!

### CODE REVIEW

**Comment by janup2442** [comment]
@aparna03dubey  check it out this all new index.html .

**Comment by aparna03dubey** [comment]
Well done! I think we should use shades of blue.

**Comment by janup2442** [comment]
Can we share our socials , so that I can see your idea , visually

**Comment by aparna03dubey** [comment]
> Can we share our socials , so that I can see your idea , visually
I didn't get. Please be clear

**Comment by janup2442** [comment]
Leave it . Have you seen the live page ? That I have modified ?

**Comment by aparna03dubey** [comment]
Good Job! Use blue color instead

**Pull request merged**
